### PR TITLE
Add pantheon desktop support

### PR DESCRIPTION
**Pull request by awissu**

### CODE REVIEW

**Comment by shundhammer** [comment]
SVG icon in visible format:

pattern-elementary

**Comment by awissu** [comment]
This icon is in this project: 
https://github.com/elementary/icons

**Comment by shundhammer** [comment]
> This icon is in this project: https://github.com/elementary/icons

So it's GPL V3. Okay, that clarifies the license. Thank you!

**Review by shundhammer — APPROVED** [review]
LGTM

**Pull request merged**
