### PR TITLE
Support breeze5-icons 5.55.0

### PR DESCRIPTION
**Pull request by Vogtinator**
Some files changed location - breaking symlinks.

### CODE REVIEW

**Comment by jreidinger** [comment]
in travis build still failing:

  /usr/share/icons/breeze-dark/apps/32/pattern-software-management.svg -> /usr/share/icons/breeze-dark/preferences/32/yast-software-group.svg
Add the package providing the target to BuildRequires and Requires
INFO: relinking /usr/share/icons/breeze-dark/apps/32/pattern-cli.svg -> utilities-terminal.svg (was ../../apps/32/utilities-terminal.svg)
INFO: relinking /usr/share/icons/breeze/apps/48/pattern-kde-pim.svg -> kontact.svg (was ../../apps/48/kontact.svg)
INFO: relinking /usr/share/icons/breeze/apps/32/pattern-technical-writing.svg -> kwrite.svg (was ../../apps/32/kwrite.svg)
ERROR: link target doesn't exist (neither in build root nor in installed system):
  /usr/share/icons/breeze/apps/32/pattern-software-management.svg -> /usr/share/icons/breeze/preferences/32/yast-software-group.svg


does it build locally with rake osc:build?

**Comment by Vogtinator** [comment]
The situation at the point this PR was created (five months ago!) was a deadlock. breeze5-icons could not get accepted into Tumbleweed as this package here failed to build. Fixing this package can only happen if breeze5-icons is in Tumbleweed though as otherwise travis fails.

As this PR was ignored for a very long time, there was no choice other than adding a workaround in breeze5-icons, so now just retriggering the build should work. Apparently I lack the permissions to do that myself.

**Comment by jreidinger** [comment]
@Vogtinator OK, I will retrigger it myself.

**Comment by jreidinger** [comment]
ok, now passing, so lets merge

**Pull request merged**
