### PR TITLE
Try unify

### PR DESCRIPTION
**Pull request by jreidinger**

### CODE REVIEW

**Comment by lslezak** [comment]
Code-wise it looks good. Did you build the RPMs and compare the contents with the old packages? Just to be sure we didn't overlook something...

**Comment by jreidinger** [comment]
well, I try build, but do not compare content, as %build and %files sections are identical, only decided by %if which one is used

**Comment by lslezak** [comment]
OK, I see...

I just noticed this line:
```
 BuildRequires:  yast2-qt-branding-openSUSE
```

That means for building the SLE theme you would need the openSUSE branding package. I could not find it in https://build.suse.de/project/show/SUSE:SLE-12-SP2:GA (even in the inherited packages).

Does the package build in SP2?

**Comment by jreidinger** [comment]
@lslezak in SP3 branch it is building, but I can also add condition to this line.

**Comment by lslezak** [comment]
Yes, that would be a good idea IMHO. I'd prefer less dependencies.

**Pull request merged**
