### PR TITLE
Add back missing styles and files for installation steps

### PR DESCRIPTION
**Pull request by Vogtinator**
This fixes a regression reported as bsc#963034, fate#320471 and bsc#970346.

- Got lost in commits 1bf246ff81a350ca412275dfcc4ae0b6c8587c33
  and f15b97c50d0294c7fc57a894efc6b6691695799a

Before
----------
before

After
-------
steps

Please add this to SLE 12 SP2, thanks.

### CODE REVIEW

**Comment by lslezak** [comment]
Ouch, I though these are not used anymore, I did not think about the firstboot...

Please add a new entry to `yast2-theme-SLE.changes` and bump the version using `rake version:update`. Otherwise it looks good to me.

And thanks for the screenshots! They make the review easier. :wink:

**Comment by lslezak** [comment]
I'll merge the change and add the version upgrade by myself...

**Comment by lslezak** [comment]
Thank you for your contribution!

**Comment by Vogtinator** [comment]
Thanks for merging!

In the CONTRIBUTING.md is stated:

> Do not change the VERSION and *.changes files as this could lead to conflicts.

so if you want PRs to contain those changes, that should probably be changed...

**Comment by lslezak** [comment]
I see. Yes,we should probably change that... It was intended to avoid conflicts, but that usually does not happen and we need to add one more pull request just to update version. I'll discuss that with the team...

**Pull request merged**
