### PR TITLE
Fixes for SLE installation theme

### PR DESCRIPTION
**Pull request by dgdavid**
This PR fixes some small YaST rebranding issues found in public beta. Namely, 

* The triangle icon for expanding/collapsing a combo box control doesn't change its color when the control containing it got disabled ([bsc#1183090](https://bugzilla.suse.com/show_bug.cgi?id=1183090)).

  A new _inst\_arr\_down\_disabled_ icon has been added, which is the same than _inst\_arr\_down_ but using the `rgba(255,255,255,60)` fill color used in the `QComboBox::disabled` QSS selector.

  <details>
  <summary>Show/hide screenshots</summary>

  ---

  | Before | After |
  |-|-|
  | arrow_disabled_before | arrow_disabled_after |

  </details>

* Some labels appear either, too close to the rest of widgets ([bsc#1183086](https://bugzilla.suse.com/show_bug.cgi?id=1183086)) or vertically cut-off ([bsc#1183306](https://bugzilla.suse.com/show_bug.cgi?id=1183306)). Sometimes even both.

  The `QGroupBox` titles have their origin in the left top margin but the top margin was set to a fixed 10px recently, which looks to be smaller than the font-size. Thus, the `QGroupBox` top margin has been restored for using the `ex` unit, which is [_the x-height of the font (i.e., the height of 'x')_](https://doc.qt.io/qt-5/stylesheet-reference.html#length). It's new value is _2.5ex_.

  <details>
  <summary>Show/hide screenshots</summary>

  ---

  | Before | After |
  |-|-|
  | device_type_label_before | device_type_label_after |
  | name_server_label_before | name_server_label_after | 
  | routing_table_label_before | routing_table_label_after |

  </details>

* `QGroupBox::title` _font-weight_ property is not being honored
 
  The `QGroupBox::title` [does not support the `QWidget::font` property](https://stackoverflow.com/a/2730567), reason why the _font-weight_ is not being applied. However, it can be used directly in `QGroupBox` selector, but it doesn't seem to fit with the new SLE rebranding because the rest of label are not bold.

  <details>
  <summary>Show/hide screenshots</summary>

  ---

  | Not Using the _font-weight: bold_ | Using the _font-weight: bold_ |
  | - | - |
  | device_type_label_after | bold_device_type_label |
  |  name_server_label_after | bold_name_servers_label |

  </details>

* Fix the _bold white frame around software selection window_ ([bsc#1183356](https://bugzilla.suse.com/show_bug.cgi?id=1183356))

  <details>
  <summary>Show/hide screenshots</summary>

  ---

  | Before | After |
  |-|-|
  | software_before | software_after |
  </details>

* Add small margin top to keep buttons completely visible

   <details>
  <summary>Show/hide screenshots</summary>

  ---

  | Before | After |
  |-|-|
  | patterns_before | patterns_after |

  </details>

* Add the right fixes for firstboot style (_supersedes_ https://github.com/yast/yast-theme/pull/142)
   <details>
  <summary>Show/hide screenshots</summary>

  ---

  | Before | After |
  |-|-|
  | firstboot_before | firstboot_after |

  </details>

### :memo: Notes for reviewers

* Manually tested using an _SLE-15-SP3-Online-x86_64-BuildY.135.5-Media1.iso_
* Better to review it commit by commit.

### CODE REVIEW

**Review by joseivanlopez — COMMENTED** [review]
Great work! Only what I commented you about the background in the package selector.

**Comment by dgdavid** [comment]
> Great work! Only what I commented you about the background in the package selector.

Thanks!

The `YQPackageSelector` _background-color_ [has been already fixed](https://github.com/yast/yast-theme/pull/144/commits/a3f23a0eb2330bb8cdd9843d2e4aeb9455bbb03a) and screenshot updated in PR's description.

**Review by shundhammer — APPROVED** [review]
LGTM

**Review by joseivanlopez — APPROVED** [review]

**Comment by kwwii** [comment]
Wow, really great work here! 

One suggestion: judging from the screenshots, I think that we can make all the QComboBox use font-weight:bold, as long as there won't be a list or such in which all entries are bold.

**Comment by dgdavid** [comment]
> Wow, really great work here!

Thanks :)

> One suggestion: judging from the screenshots, I think that we can make all the QComboBox use font-weight:bold, as long as there won't be a list or such in which all entries are bold.

Ooops! Not sure if related, but your comment make me realize that I wrote `QComboBox` instead `QGroupBox` in the descritpion when writing about the not honored _font-weight_ property. I'll fixed it.

Do you mean to use it in `QGroupBox`? If so, could you re-check below screenshots? I think it is weird/unexpected to have some labels in bold and some not (first screenshot (_Device type_) looks ok, but not the second (_Name Servers and Domain Seach List_))

  | Not Using the _font-weight: bold_ | Using the _font-weight: bold_ |
  | - | - |
  | device_type_label_after | bold_device_type_label |
  |  name_server_label_after | bold_name_servers_label |

**Comment by kwwii** [comment]
@dgdavid Good point, having some things bold and others normal weight looks weird. Let's leave it as-is for now.

**Pull request merged**
