### PR TITLE
Update branding

### PR DESCRIPTION
**Pull request by joseivanlopez**
SLE should represent the new SUSE brand. Existing images, animations, UI's, and other functional bits need to be updated to represent the new company identity/design.

https://jira.suse.com/browse/SLE-15714

## Screenshots

<details>
<summary>Click here to display the screenshots</summary>

| Original SLE15-SP3 | New Style  |
|---|---|
|sles1| new001 |
|sles2|new2|
|sles3|new3|
|sles5|new5|
|sles6|new6|
|sles7|new06|
|sles8|new7|
|sles9|new8|
|sles10|new9|
|sles11|new10|
|sles12|new11|
|sles_pkg1|new_pkg1|
|sles_pkg2|new_pkg2|

</details>

### CODE REVIEW

**Review by jreidinger — APPROVED** [review]

**Comment by lslezak** [comment]
It would be nice to have some screenshots in the PR, esp. for the QSS file...

**Comment by dgdavid** [comment]
Hi there!

I'm not sure if it worth it, but maybe those SVG files could be _optimized_ before including them in the yast-theme. That way, non-relevant information (like Inkscape meta information) will not be included and the weight could be significantly smaller.

To see what I meant, take a look to https://gist.github.com/dgdavid/47bedb850a20f5a13cc60aae7ea1ca49

To see a great summary about available tools for it, see https://css-tricks.com/tools-for-optimizing-svg/

Just my 2 cents ;)

**Comment by dgdavid** [comment]
> That way, non-relevant information (like Inkscape meta information) will not be included and the weight could be significantly smaller

And, as @lslezak said in IRC

> smaller files might save some memory in the XML parser at runtime [...]

**Review by lslezak — CHANGES_REQUESTED** [review]
I found some issues, I'll comment later...

**Review by lslezak — CHANGES_REQUESTED** [review]
Ok, here are my comments:

### Disabled Checkbox

| Original SLE15-SP3 | New Style  |
|---|---|
|sles6|new6|

The check mark in a disabled checkbox is too bright IMHO, it should be a bit darker to not stand out that much.

### Help Icon

new_help

The loupe icon next to the search field is too dark, it's almost invisible. It should be a bit brighter.

### Package Manager

| Original SLE15-SP3 | New Style  |
|---|---|
|sles_pkg2|new_pkg2|

The "View" menu in the package selector (top left corner) is a bit clipped, the top border is not displayed. (Note: this is not a regression, it is missing already with the original style, but there it was not that visible.)

**Comment by kwwii** [comment]
@lslezak Thanks for the review. I still need to create pixmaps for the disabled he checkboxes (and radio buttons and arrows).

As for the help icon - I cannot figure that one out on my own. I cannot open the window to introspect this to figure out what kind of element it is. I am not setting that dark color (#1f222b) as the foreground color ANYWHERE. I tried to set the color of "QY2HelpDialog" to white but it had no effect. I would greatly appreciate if someone can help me find the right selector for this.

**Comment by kwwii** [comment]
> Hi there!
> 
> I'm not sure if it worth it, but maybe those SVG files could be _optimized_ before including them in the yast-theme. That way, non-relevant information (like Inkscape meta information) will not be included and the weight could be significantly smaller (I know, they are lightweight already 😜).
> 
> To see what I meant, take a look to https://gist.github.com/dgdavid/47bedb850a20f5a13cc60aae7ea1ca49
> 
> To see a great summary about available tools for it, see https://css-tricks.com/tools-for-optimizing-svg/
> 
> Just my 2 cents ;)

I assumed that svg optimization would happen per script during the build. That would make a lot more sense, seeing as we are a design team and not developers.

**Comment by shundhammer** [comment]
This is where that loupe icon is set:

https://github.com/libyui/libyui-qt/blob/master/src/QY2HelpDialog.cc#L51

That dialog is defined as a Qt Designer .ui file here:

https://github.com/libyui/libyui-qt/blob/master/src/QHelpDialog.ui

**Comment by joseivanlopez** [comment]
I have manually checked it, and everything looks as expected, but comments from @lslezak still apply:

* Disabled checkbox is too bright
* Top border is not displayed in the package selector
* Help icon is to dark

Regarding the help icon, I have tried what @shundhammer suggested (lighter background), but it looks ugly, see:

Screenshot from 2021-02-10 12-55-42

I am not sure how to fix this problem, because the loupe is a compiled-in icon in libyui-qt, so changes would also affect to openSUSE (which uses light background).

And regarding the first two points, I am not sure if they can be easily fixed with some qss. Maybe those issues are not that important. @kwwii, do you consider we can merge as it is now?

Anyway, I am going to adapt https://github.com/openSUSE/installation-images/pull/437 in order to include *google-poppins-fonts*.

**Comment by joseivanlopez** [comment]
New fonts added to the installation media: https://github.com/openSUSE/installation-images/pull/451.

**Comment by joseivanlopez** [comment]
Self-reminder: update changes and spec files.

**Comment by kwwii** [comment]
@joseivanlopez I think that the top border issue and the help icon are things we can live with for now. The checkbox seems like a simple mistake which I just submitted a fix for.

**Review by lslezak — APPROVED** [review]

**Comment by shundhammer** [comment]
> @joseivanlopez I think that the top border issue and the help icon are things we can live with for now. 

Right; I wouldn't overengineer this. Giving the search icon in the help dialog a bit more contrast already helped to make it better visible. I don't think this is used very much; users gave up on using online help a long time ago.

**Pull request merged**
