### PR TITLE
Add pattern-deepin.svg

### PR DESCRIPTION
**Pull request by hillwoodroc**
Deepin project uses GPL-3+ license. Refer https://commons.wikimedia.org/wiki/File:Deepin_logo.svg

### CODE REVIEW

**Comment by lslezak** [comment]
Please add a [changelog](https://github.com/yast/yast-theme/blob/master/package/yast2-theme.changes) entry with `bsc#1185353` tag and bump the version in the [spec file](https://github.com/yast/yast-theme/blob/master/package/yast2-theme.spec) (just run `rake version:bump`).

**Comment by hillwoodroc** [comment]
> Please add a [changelog](https://github.com/yast/yast-theme/blob/master/package/yast2-theme.changes) entry with `bsc#1185353` tag and bump the version in the [spec file](https://github.com/yast/yast-theme/blob/master/package/yast2-theme.spec) (just run `rake version:bump`).

The pull request is updated.

**Review by lslezak — APPROVED** [review]
Thank you! :+1:

**Comment by shundhammer** [comment]
> Deepin project uses GPL-3+ license. Refer https://commons.wikimedia.org/wiki/File:Deepin_logo.svg

Thank you; this is an important piece of information. Right now this package is licensed as "GPL 2.0 only":

https://github.com/yast/yast-theme/blob/master/package/yast2-theme.spec#L69
https://github.com/yast/yast-theme/blob/master/COPYING

That probably means that we now have a problem with incompatible licenses.

**Comment by lslezak** [comment]
I checked other packages and some of them use multiple licenses in form of `GPL-2.0-or-later AND GPL-3.0-or-later`.

So it seems that in this case we would need to change the license from `GPL-2.0-only` to `GPL-2.0-only AND GPL-3.0-or-later` probably with explicitly stating which files are covered by which license.

**Comment by shundhammer** [comment]
This PR has become part of PR #147 which also handles the license formalities.
Closing this one.

**Pull request closed without merging**
