### PR TITLE
Add icons for MATE pattern

### PR DESCRIPTION
**Pull request by posophe**
Add MATE icons to be displayed correctly in package manager

### CODE REVIEW

**Comment by jreidinger** [comment]
it looks nice, thanks for adding it. Just why svg is named `start-here`? I think it is not correct name

**Comment by jreidinger** [comment]
@posophe ping

**Comment by posophe** [comment]
Oh yep sorry. I'll fix it tonight.

**Comment by jreidinger** [comment]
please also make it mergable, so I can merge it immediatelly

**Pull request closed without merging**
