### PR TITLE
Fix the icons' style and minify them

### PR DESCRIPTION
**Pull request by hellcp**
This also adds icons for sway-openSUSE as per sway maintainer requests, as well as moves the cinnamon icon to breeze, and replaces the old icon with one that fits the rest of the desktop patterns

### CODE REVIEW

**Review by joseivanlopez — APPROVED** [review]
LGTM

**Comment by shenlebantongying** [comment]
Ping. Is there a schedule for this to be merged?

**Comment by dgdavid** [comment]
@joseivanlopez, @hellcp,

Still this PR relevant? If so, I can help to solve conflicts and merge it.

**Comment by hellcp** [comment]
It is still relevant

**Comment by dgdavid** [comment]
Closing it in favor of #148 and #149

**Pull request closed without merging**
